name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: apt
      run: which apt-get >/dev/null && sudo apt-get -yq update && sudo apt-get -yq install build-essential libcurl4-gnutls-dev automake autoconf || true
    - name: brew
      run: which brew >/dev/null && brew install automake autoconf || true
    - name: pacman
      run: which pacman >/dev/null && pacman --noconfirm -Suy autoconf automake || true
    - name: Install Roswell
      env:
       LISP: ${{ matrix.lisp }}
       ROSWELL_BRANCH: master
      run: |
       curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
    - name: Install Rove
      run: ros install rove
