name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-18.04, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: apt
      run: which apt-get >/dev/null && sudo apt-get -yq update && sudo apt-get -yq install build-essential libcurl4-gnutls-dev automake autoconf
    - name: Install Roswell
      env:
       LISP: ${{ matrix.lisp }}
       ROSWELL_BRANCH: master
       ROSWELL_INSTALL_DIR: /usr
      run: |
       curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
    - name: Install Rove
      run: ros install rove
